// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dem_service.proto

#include "dem_service.pb.h"
#include "dem_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace dem_service {

static const char* Heighter_method_names[] = {
  "/dem_service.Heighter/GetHeight",
};

std::unique_ptr< Heighter::Stub> Heighter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Heighter::Stub> stub(new Heighter::Stub(channel, options));
  return stub;
}

Heighter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetHeight_(Heighter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Heighter::Stub::GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::dem_service::GetHeightReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetHeight_, context, request, response);
}

void Heighter::Stub::async::GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHeight_, context, request, response, std::move(f));
}

void Heighter::Stub::async::GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetHeight_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>* Heighter::Stub::PrepareAsyncGetHeightRaw(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::dem_service::GetHeightReply, ::dem_service::GetHeightRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetHeight_, context, request);
}

::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>* Heighter::Stub::AsyncGetHeightRaw(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetHeightRaw(context, request, cq);
  result->StartCall();
  return result;
}

Heighter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Heighter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Heighter::Service, ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Heighter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::dem_service::GetHeightRequest* req,
             ::dem_service::GetHeightReply* resp) {
               return service->GetHeight(ctx, req, resp);
             }, this)));
}

Heighter::Service::~Service() {
}

::grpc::Status Heighter::Service::GetHeight(::grpc::ServerContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace dem_service

