// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dem_service.proto

#include "dem_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dem_service {
PROTOBUF_CONSTEXPR GetHeightRequest::GetHeightRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wkts_)*/{}
  , /*decltype(_impl_.is_trans_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetHeightRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetHeightRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetHeightRequestDefaultTypeInternal() {}
  union {
    GetHeightRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetHeightRequestDefaultTypeInternal _GetHeightRequest_default_instance_;
PROTOBUF_CONSTEXPR GetHeightReply::GetHeightReply(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wkts_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct GetHeightReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetHeightReplyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetHeightReplyDefaultTypeInternal() {}
  union {
    GetHeightReply _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetHeightReplyDefaultTypeInternal _GetHeightReply_default_instance_;
}  // namespace dem_service
static ::_pb::Metadata file_level_metadata_dem_5fservice_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_dem_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dem_5fservice_2eproto = nullptr;

const uint32_t TableStruct_dem_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dem_service::GetHeightRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dem_service::GetHeightRequest, _impl_.wkts_),
  PROTOBUF_FIELD_OFFSET(::dem_service::GetHeightRequest, _impl_.is_trans_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dem_service::GetHeightReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dem_service::GetHeightReply, _impl_.wkts_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dem_service::GetHeightRequest)},
  { 8, -1, -1, sizeof(::dem_service::GetHeightReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dem_service::_GetHeightRequest_default_instance_._instance,
  &::dem_service::_GetHeightReply_default_instance_._instance,
};

const char descriptor_table_protodef_dem_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021dem_service.proto\022\013dem_service\"2\n\020GetH"
  "eightRequest\022\014\n\004wkts\030\001 \003(\t\022\020\n\010is_trans\030\002"
  " \001(\010\"\036\n\016GetHeightReply\022\014\n\004wkts\030\001 \003(\t2U\n\010"
  "Heighter\022I\n\tGetHeight\022\035.dem_service.GetH"
  "eightRequest\032\033.dem_service.GetHeightRepl"
  "y\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_dem_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dem_5fservice_2eproto = {
    false, false, 211, descriptor_table_protodef_dem_5fservice_2eproto,
    "dem_service.proto",
    &descriptor_table_dem_5fservice_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_dem_5fservice_2eproto::offsets,
    file_level_metadata_dem_5fservice_2eproto, file_level_enum_descriptors_dem_5fservice_2eproto,
    file_level_service_descriptors_dem_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dem_5fservice_2eproto_getter() {
  return &descriptor_table_dem_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dem_5fservice_2eproto(&descriptor_table_dem_5fservice_2eproto);
namespace dem_service {

// ===================================================================

class GetHeightRequest::_Internal {
 public:
};

GetHeightRequest::GetHeightRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dem_service.GetHeightRequest)
}
GetHeightRequest::GetHeightRequest(const GetHeightRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetHeightRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wkts_){from._impl_.wkts_}
    , decltype(_impl_.is_trans_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.is_trans_ = from._impl_.is_trans_;
  // @@protoc_insertion_point(copy_constructor:dem_service.GetHeightRequest)
}

inline void GetHeightRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.wkts_){arena}
    , decltype(_impl_.is_trans_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetHeightRequest::~GetHeightRequest() {
  // @@protoc_insertion_point(destructor:dem_service.GetHeightRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetHeightRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.wkts_.~RepeatedPtrField();
}

void GetHeightRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetHeightRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dem_service.GetHeightRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wkts_.Clear();
  _impl_.is_trans_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetHeightRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string wkts = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_wkts();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "dem_service.GetHeightRequest.wkts"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // bool is_trans = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.is_trans_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetHeightRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dem_service.GetHeightRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string wkts = 1;
  for (int i = 0, n = this->_internal_wkts_size(); i < n; i++) {
    const auto& s = this->_internal_wkts(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dem_service.GetHeightRequest.wkts");
    target = stream->WriteString(1, s, target);
  }

  // bool is_trans = 2;
  if (this->_internal_is_trans() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_is_trans(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dem_service.GetHeightRequest)
  return target;
}

size_t GetHeightRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dem_service.GetHeightRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string wkts = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.wkts_.size());
  for (int i = 0, n = _impl_.wkts_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.wkts_.Get(i));
  }

  // bool is_trans = 2;
  if (this->_internal_is_trans() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetHeightRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetHeightRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetHeightRequest::GetClassData() const { return &_class_data_; }


void GetHeightRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetHeightRequest*>(&to_msg);
  auto& from = static_cast<const GetHeightRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dem_service.GetHeightRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.wkts_.MergeFrom(from._impl_.wkts_);
  if (from._internal_is_trans() != 0) {
    _this->_internal_set_is_trans(from._internal_is_trans());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetHeightRequest::CopyFrom(const GetHeightRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dem_service.GetHeightRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetHeightRequest::IsInitialized() const {
  return true;
}

void GetHeightRequest::InternalSwap(GetHeightRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.wkts_.InternalSwap(&other->_impl_.wkts_);
  swap(_impl_.is_trans_, other->_impl_.is_trans_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetHeightRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dem_5fservice_2eproto_getter, &descriptor_table_dem_5fservice_2eproto_once,
      file_level_metadata_dem_5fservice_2eproto[0]);
}

// ===================================================================

class GetHeightReply::_Internal {
 public:
};

GetHeightReply::GetHeightReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dem_service.GetHeightReply)
}
GetHeightReply::GetHeightReply(const GetHeightReply& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  GetHeightReply* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wkts_){from._impl_.wkts_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dem_service.GetHeightReply)
}

inline void GetHeightReply::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.wkts_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

GetHeightReply::~GetHeightReply() {
  // @@protoc_insertion_point(destructor:dem_service.GetHeightReply)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void GetHeightReply::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.wkts_.~RepeatedPtrField();
}

void GetHeightReply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void GetHeightReply::Clear() {
// @@protoc_insertion_point(message_clear_start:dem_service.GetHeightReply)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.wkts_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GetHeightReply::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string wkts = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_wkts();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "dem_service.GetHeightReply.wkts"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GetHeightReply::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dem_service.GetHeightReply)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string wkts = 1;
  for (int i = 0, n = this->_internal_wkts_size(); i < n; i++) {
    const auto& s = this->_internal_wkts(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "dem_service.GetHeightReply.wkts");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dem_service.GetHeightReply)
  return target;
}

size_t GetHeightReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dem_service.GetHeightReply)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string wkts = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.wkts_.size());
  for (int i = 0, n = _impl_.wkts_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.wkts_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GetHeightReply::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    GetHeightReply::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetHeightReply::GetClassData() const { return &_class_data_; }


void GetHeightReply::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<GetHeightReply*>(&to_msg);
  auto& from = static_cast<const GetHeightReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dem_service.GetHeightReply)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.wkts_.MergeFrom(from._impl_.wkts_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GetHeightReply::CopyFrom(const GetHeightReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dem_service.GetHeightReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetHeightReply::IsInitialized() const {
  return true;
}

void GetHeightReply::InternalSwap(GetHeightReply* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.wkts_.InternalSwap(&other->_impl_.wkts_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GetHeightReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dem_5fservice_2eproto_getter, &descriptor_table_dem_5fservice_2eproto_once,
      file_level_metadata_dem_5fservice_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace dem_service
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dem_service::GetHeightRequest*
Arena::CreateMaybeMessage< ::dem_service::GetHeightRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dem_service::GetHeightRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::dem_service::GetHeightReply*
Arena::CreateMaybeMessage< ::dem_service::GetHeightReply >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dem_service::GetHeightReply >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
