// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: dem_service.proto
#ifndef GRPC_dem_5fservice_2eproto__INCLUDED
#define GRPC_dem_5fservice_2eproto__INCLUDED

#include "dem_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace dem_service {

class Heighter final {
 public:
  static constexpr char const* service_full_name() {
    return "dem_service.Heighter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::dem_service::GetHeightReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dem_service::GetHeightReply>> AsyncGetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dem_service::GetHeightReply>>(AsyncGetHeightRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dem_service::GetHeightReply>> PrepareAsyncGetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dem_service::GetHeightReply>>(PrepareAsyncGetHeightRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dem_service::GetHeightReply>* AsyncGetHeightRaw(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dem_service::GetHeightReply>* PrepareAsyncGetHeightRaw(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::dem_service::GetHeightReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>> AsyncGetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>>(AsyncGetHeightRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>> PrepareAsyncGetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>>(PrepareAsyncGetHeightRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response, std::function<void(::grpc::Status)>) override;
      void GetHeight(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>* AsyncGetHeightRaw(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dem_service::GetHeightReply>* PrepareAsyncGetHeightRaw(::grpc::ClientContext* context, const ::dem_service::GetHeightRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetHeight_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetHeight(::grpc::ServerContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetHeight : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetHeight() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetHeight() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHeight(::grpc::ServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHeight(::grpc::ServerContext* context, ::dem_service::GetHeightRequest* request, ::grpc::ServerAsyncResponseWriter< ::dem_service::GetHeightReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetHeight<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetHeight : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetHeight() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dem_service::GetHeightRequest* request, ::dem_service::GetHeightReply* response) { return this->GetHeight(context, request, response); }));}
    void SetMessageAllocatorFor_GetHeight(
        ::grpc::MessageAllocator< ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetHeight() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHeight(::grpc::ServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHeight(
      ::grpc::CallbackServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetHeight<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetHeight : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetHeight() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetHeight() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHeight(::grpc::ServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetHeight : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetHeight() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetHeight() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHeight(::grpc::ServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetHeight(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetHeight : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetHeight() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetHeight(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetHeight() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetHeight(::grpc::ServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetHeight(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetHeight : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetHeight() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dem_service::GetHeightRequest, ::dem_service::GetHeightReply>* streamer) {
                       return this->StreamedGetHeight(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetHeight() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetHeight(::grpc::ServerContext* /*context*/, const ::dem_service::GetHeightRequest* /*request*/, ::dem_service::GetHeightReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetHeight(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dem_service::GetHeightRequest,::dem_service::GetHeightReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetHeight<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetHeight<Service > StreamedService;
};

}  // namespace dem_service


#endif  // GRPC_dem_5fservice_2eproto__INCLUDED
